- name: Demo on play level variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: display the variable
      ansible.builtin.debug:
        msg: URL is - {{ URL }}

- name: Demo on task level variable
  hosts: all
  tasks:
    - name: display the task level variable
      ansible.builtin.debug:
        msg: URL is - {{ URL }}
      vars:
        URL: tasks.example.com

- name: Demo on task level variable
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: display the task level variabke
      ansible.builtin.debug:
        msg: URL is - {{ URL }}

- name: Demo on role level variable
  hosts: all
  roles:
    - sample


