- name: Demo on play level variables
  hosts: all
  vars:
    URL = play.example.com
  tasks:
    - name: display the variable
      ansible.builtin.msg:
        msg: URL is - {{ URL }}

- name: Demo on task level variable
  hosts: all
  tasks:
    - name: display the task level variable
      ansible.builtin.msg:
        msg: URL is - {{ URL }}
      vars:
        URL = tasks.example.com

- name: Demo on task level variable
  hosts: all
  vars:
    exvars.yml
  tasks:
    - name: display the task level variabke
      ansible.builtin.msg:
        msg: URL is - {{ URL }}


